name: trexxo_mobility
description: "Cab Booking App for Android and iOS using Flutter"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # ui elements
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  icons_plus: ^5.0.0

  # cloud and state management
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0
  equatable: ^2.0.7

  # services
  google_maps_flutter: ^2.12.2
  flutter_google_places_sdk: ^0.4.2+1

  # tools
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  path_provider: ^2.1.5
  geocoding: ^4.0.0

  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/app/
    - assets/images/
    - assets/others/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
